/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.umranium.longmark.ui;

import com.umranium.longmark.model.Document;
import com.umranium.longmark.model.DocumentSection;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.JButton;
import javax.swing.JSpinner;
import org.jdesktop.beansbinding.AutoBinding;
import org.jdesktop.beansbinding.BeanProperty;
import org.jdesktop.beansbinding.Binding;
import org.jdesktop.beansbinding.BindingGroup;
import org.jdesktop.beansbinding.Bindings;
import org.jdesktop.beansbinding.ObjectProperty;

/**
 *
 * @author umran
 */
public class MarkingPanel extends javax.swing.JPanel {
    
    private DocumentSection docSection;
    private MultiColumnText commentsTxt;
    
    private BindingGroup bindingGroup;

    /**
     * Creates new form MarkingPanel
     */
    public MarkingPanel(DocumentSection docSection, int columns, int rows) {
        commentsTxt = new MultiColumnText(columns, rows);
        initComponents();
        commentsTxt.setText("Hey\nKya bolti tu\nKya me bolu\n");
        
        
//        docSection.addPropertyChangeListener(DocumentSection.PROP_COMMENTS,
//                new PropertyChangeListener() {
//            @Override
//            public void propertyChange(PropertyChangeEvent evt) {
//                String newVal = (String)evt.getNewValue();
//                commentsTxt.setText(newVal);
//            }
//        });
        
        
        bindingGroup = new BindingGroup();
        Binding markBinding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                docSection,
                BeanProperty.create(DocumentSection.PROP_MARK),
                marksSpinner,
                BeanProperty.create("value"));
        Binding commentsBinding = Bindings.createAutoBinding(
                AutoBinding.UpdateStrategy.READ_WRITE,
                docSection,
                BeanProperty.create(DocumentSection.PROP_COMMENTS),
                commentsTxt,
                BeanProperty.create(MultiColumnText.PROP_TEXT));
        bindingGroup.addBinding(markBinding);
        bindingGroup.addBinding(commentsBinding);
        bindingGroup.bind();
        
        /**
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();
        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ObjectProperty.create(), marksSpinner, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);
        bindingGroup.bind();
         **/
    }
    
    public MultiColumnText getCommentsTxt() {
        return commentsTxt;
    }
    
    public JSpinner getMarksSpinner() {
        return marksSpinner;
    }

    public JButton getEditCommentsBtn() {
        return editCommentsBtn;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        javax.swing.JPanel jPanel1 = commentsTxt;
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        marksSpinner = new javax.swing.JSpinner();
        editCommentsBtn = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.GridBagLayout());

        marksSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(0.0d), Double.valueOf(0.0d), null, Double.valueOf(0.5d)));
        marksSpinner.setPreferredSize(new java.awt.Dimension(100, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(marksSpinner, gridBagConstraints);

        editCommentsBtn.setText("Edit Comment");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(editCommentsBtn, gridBagConstraints);

        add(jPanel2, java.awt.BorderLayout.EAST);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editCommentsBtn;
    private javax.swing.JSpinner marksSpinner;
    // End of variables declaration//GEN-END:variables
}
