/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.umranium.longmark.ui.doc;

import com.umranium.longmark.model.Document;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author umran
 */
public class DocSecGridHeader extends javax.swing.JPanel {
    
    private DocSecGridPanel gridPanel;

    /**
     * Creates new form DocSecGridHeader
     */
    public DocSecGridHeader(DocSecGridPanel gridPanel) {
        this.gridPanel = gridPanel;
        initComponents();
    }
    
    public void addDocument(Document doc) {
        int column = gridPanel.getDocumentColumn(doc);
        DocTitle documentTitle = new DocTitle(doc, this, gridPanel);
        System.out.println("Added Document Header "+doc.getSource()+" to column "+column);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridx = column;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.NONE;
        //gbc.insets = new Insets(5, 5, 5, 5);
        this.add(documentTitle, gbc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setLayout(new java.awt.GridBagLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
