/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.umranium.longmark.ui.doc;

import com.umranium.longmark.model.Document;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.List;

/**
 *
 * @author umran
 */
public class DocTitle extends javax.swing.JPanel {
    
    private Document document;
    private DocSecGridHeader gridHeader;
    private DocSecGridPanel gridPanel;

    /**
     * Creates new form DocTitle
     */
    public DocTitle(Document document, DocSecGridHeader gridHeader, DocSecGridPanel gridPanel) {
        this.document = document;
        this.gridHeader = gridHeader;
        this.gridPanel = gridPanel;
        initComponents();
        lblTitle.setText(document.getSource());
        this.revalidate();
    }

    @Override
    public Dimension getPreferredSize() {
        Dimension dim = super.getPreferredSize();
        int maxWidth = 0;
        
        GridBagLayout gridBagLayout = (GridBagLayout)gridPanel.getLayout();
        int column = gridPanel.getDocumentColumn(document);
        
        int[][] dims = gridBagLayout.getLayoutDimensions();
        if (column<dims[0].length) {
            maxWidth = dims[0][column];
        }
        
        if (column==0 || column==gridPanel.getColumnCount()-1) {
            maxWidth -= 3; // for the header's border
        }
        
        return new Dimension(maxWidth, dim.height);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setLayout(new java.awt.BorderLayout());

        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(lblTitle, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
